export const data = [
  {
    id: 0,
    number: 1,
    exhausters: [
      {
        id: 0,
        name: "У-171",
        rotorNumber: "35к",
        rotorDate: "12.02.2023",
        rotorPrognosys: "12 сут",
        sensors: [
          {
            id: 0,
            name: "№1 п-к",
            temperature: 10,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 1,
            name: "№2 п-к",
            temperature: 10,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 2,
            name: "№3 п-к",
            temperature: 10,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 3,
            name: "№4 п-к",
            temperature: 10,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 4,
            name: "№5 п-к",
            temperature: 10,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 5,
            name: "№6 п-к",
            temperature: 10,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 6,
            name: "№7 п-к",
            temperature: 10,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 7,
            name: "№8 п-к",
            temperature: 10,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 8,
            name: "№9 п-к",
            temperature: 10,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 10,
            name: "Охладитель",
            temperatureBefore: 40,
            temperatureAfter: 40,
          },
          {
            id: 11,
            name: "Газовый коллектор",
            temperatureBefore: 40,
            temperatureAfter: 40,
          },
          {
            id: 12,
            name: "Положение задвижки",
            valvePosition: 40,
          },
          {
            id: 13,
            name: "Главный привод",
            rotorCurrent: 10,
            rotorVoltage: 10,
            statorCurrent: 10,
            statorVoltage: 10,
          },
          {
            id: 14,
            name: "Маслосистема",
            oillevel: 10,
            oilPressure: 10,
          },
        ]
      },
      {
        id: 1,
        name: "У-172",
        rotorNumber: "47",
        rotorDate: "24.02.2023",
        rotorPrognosys: "25 сут",
        sensors: [
          {
            id: 0,
            name: "№1 п-к",
            temperature: 40,
            vibrationAxial: 20,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 1,
            name: "№2 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 2,
            name: "№3 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 3,
            name: "№4 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 4,
            name: "№5 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 5,
            name: "№6 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 6,
            name: "№7 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 7,
            name: "№8 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 8,
            name: "№9 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 10,
            name: "Охладитель",
            temperatureBefore: 40,
            temperatureAfter: 40,
          },
          {
            id: 11,
            name: "Газовый коллектор",
            temperatureBefore: 40,
            temperatureAfter: 40,
          },
          {
            id: 12,
            name: "Положение задвижки",
            valvePosition: 40,
          },
          {
            id: 13,
            name: "Главный привод",
            rotorCurrent: 10,
            rotorVoltage: 10,
            statorCurrent: 10,
            statorVoltage: 10,
          },
          {
            id: 14,
            name: "Маслосистема",
            oillevel: 10,
            oilPressure: 10,
          },
        ]
      },
    ]
  },
  {
    id: 1,
    number: 2,
    exhausters: [
      {
        id: 2,
        name: "Ф-171",
        rotorNumber: "37",
        rotorDate: "02.02.2023",
        rotorPrognosys: "15 сут",
        sensors: [
          {
            id: 0,
            name: "№1 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 1,
            name: "№2 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 2,
            name: "№3 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 3,
            name: "№4 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 4,
            name: "№5 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 5,
            name: "№6 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 6,
            name: "№7 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 7,
            name: "№8 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 8,
            name: "№9 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 10,
            name: "Охладитель",
            temperatureBefore: 40,
            temperatureAfter: 40,
          },
          {
            id: 11,
            name: "Газовый коллектор",
            temperatureBefore: 40,
            temperatureAfter: 40,
          },
          {
            id: 12,
            name: "Положение задвижки",
            valvePosition: 40,
          },
          {
            id: 13,
            name: "Главный привод",
            rotorCurrent: 10,
            rotorVoltage: 10,
            statorCurrent: 10,
            statorVoltage: 10,
          },
          {
            id: 14,
            name: "Маслосистема",
            oillevel: 10,
            oilPressure: 10,
          },
        ]
      },
      {
        id: 3,
        name: "Ф-172",
        rotorNumber: "57",
        rotorDate: "13.02.2023",
        rotorPrognosys: "5 сут",
        sensors: [
          {
            id: 0,
            name: "№1 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 1,
            name: "№2 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 2,
            name: "№3 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 3,
            name: "№4 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 4,
            name: "№5 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 5,
            name: "№6 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 6,
            name: "№7 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 7,
            name: "№8 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 8,
            name: "№9 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 10,
            name: "Охладитель",
            temperatureBefore: 40,
            temperatureAfter: 40,
          },
          {
            id: 11,
            name: "Газовый коллектор",
            temperatureBefore: 40,
            temperatureAfter: 40,
          },
          {
            id: 12,
            name: "Положение задвижки",
            valvePosition: 40,
          },
          {
            id: 13,
            name: "Главный привод",
            rotorCurrent: 10,
            rotorVoltage: 10,
            statorCurrent: 10,
            statorVoltage: 10,
          },
          {
            id: 14,
            name: "Маслосистема",
            oillevel: 10,
            oilPressure: 10,
          },
        ]
      },
    ]
  },
  {
    id: 2,
    number: 3,
    exhausters: [
      {
        id: 4,
        name: "Х-171",
        rotorNumber: "39",
        rotorDate: "25.01.2023",
        rotorPrognosys: "12 сут",
        sensors: [
          {
            id: 0,
            name: "№1 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 1,
            name: "№2 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 2,
            name: "№3 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 3,
            name: "№4 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 4,
            name: "№5 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 5,
            name: "№6 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 6,
            name: "№7 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 7,
            name: "№8 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 8,
            name: "№9 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 10,
            name: "Охладитель",
            temperatureBefore: 40,
            temperatureAfter: 40,
          },
          {
            id: 11,
            name: "Газовый коллектор",
            temperatureBefore: 40,
            temperatureAfter: 40,
          },
          {
            id: 12,
            name: "Положение задвижки",
            valvePosition: 40,
          },
          {
            id: 13,
            name: "Главный привод",
            rotorCurrent: 10,
            rotorVoltage: 10,
            statorCurrent: 10,
            statorVoltage: 10,
          },
          {
            id: 14,
            name: "Маслосистема",
            oillevel: 10,
            oilPressure: 10,
          },
        ]
      },
      {
        id: 5,
        name: "Х-172",
        rotorNumber: "45",
        rotorDate: "06.02.2023",
        rotorPrognosys: "25 сут",
        sensors: [
          {
            id: 0,
            name: "№1 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 1,
            name: "№2 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 2,
            name: "№3 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 3,
            name: "№4 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 4,
            name: "№5 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 5,
            name: "№6 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 6,
            name: "№7 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 7,
            name: "№8 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 8,
            name: "№9 п-к",
            temperature: 40,
            vibrationAxial: 10,
            vibrationHorizontal: 10,
            vibrationVertical: 10,
          },
          {
            id: 10,
            name: "Охладитель",
            temperatureBefore: 40,
            temperatureAfter: 40,
          },
          {
            id: 11,
            name: "Газовый коллектор",
            temperatureBefore: 40,
            temperatureAfter: 40,
          },
          {
            id: 12,
            name: "Положение задвижки",
            valvePosition: 40,
          },
          {
            id: 13,
            name: "Главный привод",
            rotorCurrent: 10,
            rotorVoltage: 10,
            statorCurrent: 10,
            statorVoltage: 10,
          },
          {
            id: 14,
            name: "Маслосистема",
            oillevel: 10,
            oilPressure: 10,
          },
        ]
      },
    ]
  },
]
